kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: tls-proxy
  labels:
    app: tls-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: tls-proxy
      name: tls-proxy
    spec:
      containers:
        - name: tls-proxy
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 443
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 250M
            requests:
              cpu: 500m
              memory: 250M
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: certbot
              mountPath: /etc/nginx/ssl
      volumes:
        - name: certbot
          secret:
            secretName: certbot
            defaultMode: 0600
            items:
            - key: fullchain.pem
              path: server.crt
              mode: 0400
            - key: privkey.pem
              path: server.key
              mode: 0400
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tls-proxy
  namespace: default
  labels:
    app: tls-proxy
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: tls-proxy
  type: LoadBalancer
